FROM ruby:3.4.4

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install -y nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install latest Rails
RUN gem install rails

WORKDIR /app

# This will be used to generate the Rails app
CMD ["rails", "new", ".", "--name=rails_stack_demo", "--database=postgresql", "--skip-git"]
